export * from 'eslint-preset-astro/configs'
export * from 'eslint-preset-basic/configs'
export * from 'eslint-preset-solid/configs'
export * from 'eslint-preset-react/configs'
export * from 'eslint-preset-vue/configs'
